
version: '3.8'

services:
 web:
  build:
   context: ./backend
  ports:
  - 5000:5000
  volumes:
  - .:/backend
  stdin_open: true   
  tty: true   

 mysqldb:
  image: mysql
  ports:
  - 3306:3306
  environment:
  - MYSQL_DATABASE=todo_db
  - MYSQL_ROOT_PASSWORD=abc123
  - MYSQL_ROOT_HOST=%
  volumes:
  - mysql:/var/lib/mysql
  - mysql_config:/etc/mysql

 vite:
  ports:
  - 3000:3000
  build:
   context: ./frontend
  volumes:
   - .:/frontend
volumes:
  mysql:
  mysql_config:

